--query table film
CREATE TABLE FILM (ID_FILM CHAR(5) NOT NULL, TITLE VARCHAR2(35),DIRECTOR VARCHAR2(35), CAST_MEMBER VARCHAR2(100), DURATION VARCHAR2(10), RATING VARCHAR(5),GENRE VARCHAR2(100),SINOPSIS VARCHAR2(400));


INSERT INTO FILM (ID_FILM,TITLE,DIRECTOR,CAST_MEMBER,DURATION,RATING,GENRE,SINOPSIS) VALUES ('MID01','Onward','Dan Scanlon','Tom Holland, Chris Pratt, Octavia Spencer,Julia Louis-Dreyfus, Ali Wong','102 mnt','PG','Adventure, Animation, Comedy, Family, Fantasy',
'In a suburban fantasy world, two teenage elf brothers, Ian and Barley Lightfoot, go on a journey to discover if there is still a little magic left out there in order 
to spend one last day with their father, who died when they were too young to remember him.');

INSERT INTO FILM (ID_FILM,TITLE,DIRECTOR,CAST_MEMBER,DURATION,RATING,GENRE,SINOPSIS) VALUES ('MID02','Rebecca','Ben Wheatley','Lily James, Armie Hammer, Kristin Scott Thomas','121 mnt','PG-13','Drama, Mystery, Romance, Thriller',
'A young newlywed arrives at her husbands imposing family estate on a windswept English coast and finds herself battling the shadow of his first wife, Rebecca, whose legacy lives on in the house long after her death.');

INSERT INTO FILM (ID_FILM,TITLE,DIRECTOR,CAST_MEMBER,DURATION,RATING,GENRE,SINOPSIS) VALUES ('MID03','Love and Monsters','Michael Matthews',' Dylan OBrien, Jessica Henwick, Michael Rooker','109 mnt','PG-13','Action, Adventure, Comedy',
'In a monster-infested world, Joel learns his girlfriend is just 80 miles away. To make the dangerous journey, Joel discovers his inner hero to be with the girl of his dreams.');

INSERT INTO FILM (ID_FILM,TITLE,DIRECTOR,CAST_MEMBER,DURATION,RATING,GENRE,SINOPSIS) VALUES ('MID04','The Devil All the Time','Antonio Campos','Donald Ray Pollock, Bill Skarsgård, Tom Holland, Robert Pattinson','129 mnt','R','Crime, Drama, Thriller',
'Sinister characters converge around a young man devoted to protecting those he loves in a postwar backwoods town teeming with corruption and brutality.');

INSERT INTO FILM (ID_FILM,TITLE,DIRECTOR,CAST_MEMBER,DURATION,RATING,GENRE,SINOPSIS) VALUES ('MID05','Tenet','Christopher Nolan','John David Washington, Robert Pattinson, Elizabeth Debicki','150 mnt','PG-13','Action, Sci-Fi',
'Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.');

INSERT INTO FILM (ID_FILM,TITLE,DIRECTOR,CAST_MEMBER,DURATION,RATING,GENRE,SINOPSIS) VALUES ('MID06','Wonder Woman 1984','Patty Jenkins','Pedro Pascal, Connie Nielsen, Chris Pine, Gal Gadot','151 mnt','PG-13','Action, Adventure, Fantasy',
'Fast forward to the 1980s as Wonder Womans next big screen adventure finds her facing two all-new foes: Max Lord and The Cheetah.');

INSERT INTO FILM (ID_FILM,TITLE,DIRECTOR,CAST_MEMBER,DURATION,RATING,GENRE,SINOPSIS) VALUES ('MID07','Resistance','Jonathan Jakubowicz','Jesse Eisenberg, Clémence Poésy, Matthias Schweighöfer','120 mnt','R','Biography, Drama, History, War',
'The story of mime Marcel Marceau as he works with a group of Jewish boy scouts and the French Resistance to save the lives of ten thousand orphans during World War II.');

INSERT INTO FILM (ID_FILM,TITLE,DIRECTOR,CAST_MEMBER,DURATION,RATING,GENRE,SINOPSIS) VALUES ('MID08','Trolls World Tour','Walt Dohrn, David P. Smith','Anna Kendrick, Justin Timberlake, Rachel Bloom','90 mnt','PG','Animation, Adventure, Family, Fantasy, Musical',
'When the Queen of the Hard Rock Trolls tries to take over all the Troll kingdoms, Queen Poppy and her friends try different ways to save all the Trolls.');

ALTER TABLE FILM ADD PRIMARY KEY(ID_FILM);

SELECT * FROM FILM;

--query table kursi
CREATE TABLE CHAIR (CHAIR_NO CHAR(3),STATUS CHAR(5));

INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('A01','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('A02','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('A03','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('A04','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('A05','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('A06','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('A07','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('A08','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('A09','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('A10','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('A11','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('A12','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('A13','EMPTY');

INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('B01','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('B02','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('B03','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('B04','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('B05','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('B06','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('B07','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('B08','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('B09','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('B10','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('B11','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('B12','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('B13','EMPTY');

INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('C01','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('C02','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('C03','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('C04','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('C05','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('C06','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('C07','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('C08','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('C09','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('C10','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('C11','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('C12','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('C13','EMPTY');

INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('D01','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('D02','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('D03','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('D04','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('D05','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('D06','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('D07','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('D08','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('D09','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('D10','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('D11','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('D12','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('D13','EMPTY');

INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('E01','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('E02','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('E03','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('E04','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('E05','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('E06','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('E07','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('E08','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('E09','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('E10','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('E11','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('E12','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('E13','EMPTY');

INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('F01','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('F02','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('F03','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('F04','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('F05','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('F06','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('F07','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('F08','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('F09','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('F10','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('F11','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('F12','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('F13','EMPTY');

INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('G01','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('G02','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('G03','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('G04','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('G05','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('G06','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('G07','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('G08','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('G09','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('G10','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('G11','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('G12','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('G13','EMPTY');

INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('H01','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('H02','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('H03','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('H04','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('H05','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('H06','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('H07','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('H08','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('H09','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('H10','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('H11','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('H12','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('H13','EMPTY');

INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('I01','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('I02','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('I03','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('I04','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('I05','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('I06','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('I07','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('I08','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('I09','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('I10','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('I11','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('I12','EMPTY');
INSERT INTO CHAIR (CHAIR_NO, STATUS) VALUES ('I13','EMPTY');

ALTER TABLE CHAIR ADD PRIMARY KEY(CHAIR_NO);

SELECT * FROM CHAIR;

--query table ACCOUNT
CREATE TABLE ACCOUNT (ID_ACCOUNT CHAR(3)NOT NULL,FIRSTNAME VARCHAR2(20),LASTNAME VARCHAR2(20), USERNAME VARCHAR2(35), PASSWORD VARCHAR2(8), EMAIL VARCHAR(35), NO_TLP INT);

INSERT INTO ACCOUNT (ID_ACCOUNT, FIRSTNAME, LASTNAME, USERNAME, PASSWORD, EMAIL, NO_TLP) VALUES ('001','Thomas','Shelby','PeakyB','grace','ThomasShelby@gmail.com','0845276435678');

ALTER TABLE ACCOUNT ADD PRIMARY KEY(ID_ACCOUNT);

SELECT * FROM ACCOUNT;

--query table book
CREATE TABLE BOOK (ID_BOOK CHAR(17) NOT NULL, HARI CHAR(8), TGL VARCHAR2(15), JAM VARCHAR2(15), JUMLAH INT, ID_FILM CHAR(5));

ALTER TABLE BOOK ADD PRIMARY KEY(ID_BOOK);

ALTER TABLE BOOK
ADD CONSTRAINT FK_FILM FOREIGN KEY (ID_FILM) REFERENCES FILM(ID_FILM);

ALTER TABLE BOOK
ADD CONSTRAINT FK_CHAIR FOREIGN KEY (CHAIR_NO) REFERENCES CHAIR(CHAIR_NO);

ALTER TABLE BOOK
DROP CONSTRAINT FK_CHAIR;

--MO-MID01-A01-1200
--HARI-jam-RANDom number/ inceremet number (01,02)
INSERT INTO BOOK (ID_BOOK, HARI, TGL, JAM, JUMLAH, ID_FILM) VALUES ('MO1101', 'Monday','21-11-2020','12:00', 1,'MID01');
INSERT INTO BOOK (ID_BOOK, HARI, TGL, JAM, JUMLAH, ID_FILM) VALUES ('MO1302', 'Monday','21-11-2020','12:00', 1,'MID01');

SELECT * FROM BOOK;

DELETE FROM BOOK WHERE JUMLAH = '1';


--query table payment
CREATE TABLE PAYMENT (ID_PAYMENT CHAR(15),TOTAL INT, METODE VARCHAR2(10),ID_BOOK CHAR(17), ID_ACCOUNT CHAR(3));

ALTER TABLE PAYMENT ADD PRIMARY KEY(ID_PAYMENT);

--idpayment = id_book + id_account
INSERT INTO PAYMENT(ID_PAYMENT, TOTAL, METODE, ID_BOOK, ID_ACCOUNT) VALUES ('MO1302001',50000,'OVO','MO1302','001');

ALTER TABLE PAYMENT
ADD CONSTRAINT FK_ACC FOREIGN KEY (ID_ACCOUNT) REFERENCES ACCOUNT(ID_ACCOUNT);

ALTER TABLE PAYMENT
ADD CONSTRAINT FK_BOOK FOREIGN KEY (ID_BOOK) REFERENCES BOOK(ID_BOOK);

SELECT * FROM PAYMENT;

